### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/ms-user-service?createDatabaseIfNotExist=true
spring.application.name=ms-user-service
server.port=8080
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT properties
jwt.secret=14a11de4dbd006b92930205ae02f3a0fe77aa48d2c8c90b6f966b58f7121f39d
jwt.expiration-ms=3600000

# reCAPTCHA v3
recaptcha.enabled=true
recaptcha.secret=6LcJKpgsAAAAAMeg3zb9tMhCgCl_XxqI2YS72yP_
recaptcha.site-key=6LcJKpgsAAAAAJaaOIFvpHJ4J1b4SopXIQbzRNBY
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify
recaptcha.min-score=0.5
recaptcha.dev-mode-token=${RECAPTCHA_DEV_TOKEN:DEV_ONLY_BYPASS}
